version: '3.9'

services:
  app:
    build: .
    environment:
      - 'SPRING_PROFILES_ACTIVE=container'
    ports:
      - '8080:8080'
    depends_on:
      - redis
  redis:
    image: redis:6.2.6-alpine
